apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etheroscope-database-initiator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etheroscope-database-initiator
  template:
    metadata:
      labels:
        app: etheroscope-database-initiator
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: etheroscope-database-initiator-container
          image: gcr.io/etheroscope/etheroscope-database-initiator:latest
          env:
            - name: ETHEROSCOPEMARIADB
              value: "10.3.240.97:8083"