apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etheroscope-micro-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etheroscope-micro-service
  template:
    metadata:
      labels:
        app: etheroscope-micro-service
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
      - name: rinkeby-geth-volume
        gcePersistentDisk:
          pdName: rinkeby-geth-disk
          fsType: ext4
      containers:
      - name: etheroscope-micro-service-container
        image: gcr.io/etheroscope/etheroscope-micro-service:latest
        env:
        - name: ETHEROSCOPEGETHHOST
          value: "10.3.255.188:8545"
        - name: ETHEROSCOPEMARIADB
          value: "10.3.240.97:8083"
        - name: ETHEROSCOPEMICROSERVICE
          value: "35.246.65.214:80"
        - name: ETHEROSCOPESERVER
          value: "35.230.140.68:8080"
        - name: ETHEROSCOPEFRONTEND
          value: "35.242.161.116:80"
        imagePullPolicy: "Always"
        volumeMounts:
        - name: rinkeby-geth-volume
          mountPath: /usr/src/app/etheroscope/geth-blockchains/fullRinkebyBlockchain/
