kind: Service
apiVersion: v1
metadata:
  name: etheroscope-frontend-load-balancer
spec:
  selector:
    app: etheroscope-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
  type: LoadBalancer
