apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etheroscope-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etheroscope-frontend
  template:
    metadata:
      labels:
        app: etheroscope-frontend
    spec:
      containers:
        - name: etheroscope-frontend-container
          image: gcr.io/etheroscope/etheroscope-frontend
