stages:
  - build
  - deploy
  
cache:
  paths:
    - node_modules/
  
build:
  stage: build
  script:
    - npm install

deploy:
  stage: deploy
  script:
    - cp -r * /home/gitlab-runner/deploy/etheroscope
    - cd /home/gitlab-runner/deploy/etheroscope
    - killall -q gulp parity || true
    - (parity --tracing on --pruning archive --dapps-port=9090 & disown) &> /dev/null
    - node ./tools/fetchBlocks.js
    - (gulp watch-dev & disown) &> /dev/null