build:
  stage: build
  script:
    - parity --tracing on --pruning archive --dapps-port=9090; npm install; bower install

cache-blocks:
  stage: cache-blocks
  script:
    - node ./tools/fetchBlocks.js
      
run:
  stage: run
  script:
    - gulp watch-dev
