build:
  stage: build
  script:
    - npm install

killPastInstances:
  stage: deploy
  script:
    - killall -q gulp parity

startParity:
  stage: deploy
  script:
    - (parity --tracing on --pruning archive --dapps-port=9090 & disown) &> /dev/null

createCache:
  stage: deploy
  script:
    - node ./tools/fetchBlocks.js
      
run:
  stage: deploy
  script:
    - gulp watch-dev
