build:
  stage: build
  script:
    - npm install

createCache:
  stage: deploy
  script:
    - killall gulp parity; (parity --tracing on --pruning archive --dapps-port=9090 & disown) &> /dev/null; node ./tools/fetchBlocks.js
      
run:
  stage: deploy
  script:
    - gulp watch-dev
