#!/usr/bin/env node
const Web3 = require('web3')
const parityUrl = 'http://localhost:8545'
const web3 = new Web3(new Web3.providers.HttpProvider(parityUrl))
web3.eth.getBlockNumber((error, block) => {
  if (error) console.log(error)
  console.log(block)
})
