kind: Service
apiVersion: v1
metadata:
    name: etheroscope-backend
spec:
    selector:
        app: etheroscope-backend
    ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 8081
      targetPort: 8081


