apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mariadb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb-container
          image: gcr.io/etheroscope/mariadb
          env:
              - name: MYSQL_ROOT_PASSWORD
                value: "wp"
#                valueFrom:
#                  secretKeyRef:
#                      name: mariadb
#                      key: password
          ports:
#              - containerPort: 3306
#                name: mariadb
          - protocol: TCP
            port: 8083
            targetPort: 3306
          volumeMounts:
              - name: mysql-persistent-storage
                mountPath: /var/lib/mysql
      volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mariadb-volumeclaim
