apiVersion: v1
kind: Service
metadata:
    name: mariadb
    labels:
        app: mariadb
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 8083
      targetPort: 3306
    selector:
        app: mariadb
