module.exports.ETHEROSCOPEPARITYMAINNET=process.env.ETHEROSCOPEPARITYMAINNET
module.exports.ETHEROSCOPEMARIADB=process.env.ETHEROSCOPEMARIADB
module.exports.ETHEROSCOPEMICROSERVICE=process.env.ETHEROSCOPEMICROSERVICE
module.exports.ETHEROSCOPESERVER=process.env.ETHEROSCOPESERVER
module.exports.ETHEROSCOPEFRONTEND=process.env.ETHEROSCOPEFRONTEND

module.exports.dataPointsService = {
  cacheChunkSize: 10000,
  socketPort: 8081
}
