kind: Service
apiVersion: v1
metadata:
  name: etheroscope-serwer-load-balancer-8080
spec:
  selector:
    app: etheroscope-serwer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer