apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etheroscope-micro-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etheroscope-micro-service
  template:
    metadata:
      labels:
        app: etheroscope-micro-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: etheroscope-micro-service-container
        image: gcr.io/etheroscope/etheroscope-micro-service:latest
        env:
        - name: NODE_ENV
          value: "production"
        - name: DB_USERNAME
          value: "zppuser"
        - name: DB_PASSWORD
          value: "T6yt1rLPYv25"
        - name: DB_NAME
          value: "mysqldb"
        - name: DB_HOSTNAME
          value: "10.43.145.3"
        imagePullPolicy: "Always"
