kind: Service
apiVersion: v1
metadata:
  name: etheroscope-server-load-balancer-8080
spec:
  selector:
    app: etheroscope-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer