apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etheroscope-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etheroscope-server
  template:
    metadata:
      labels:
        app: etheroscope-server
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: etheroscope-server-container
        image: gcr.io/etheroscope/etheroscope-server:latest
        env:
        - name: ETHEROSCOPEPARITYMAINNET
          value: "35.246.67.158:8545"
        - name: ETHEROSCOPEGETHHOST
          #          value: "10.3.255.188:8545" # rinkeby
          value: "10.3.240.197:8545"
        - name: ETHEROSCOPEMICROSERVICE
          value: "35.246.39.252:80"
        - name: ETHEROSCOPESERVER
          value: "35.246.8.29:8080"
        - name: ETHEROSCOPEFRONTEND
          value: "35.242.160.198:80"
        - name: NODE_ENV
          value: "production"
        - name: DB_USERNAME
          value: "zppuser"
        - name: DB_PASSWORD
          value: "T6yt1rLPYv25"
        - name: DB_NAME
          value: "mysqldb"
        - name: DB_HOSTNAME
          value: "10.43.145.3"
        imagePullPolicy: "Always"
