apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parity-mainnet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parity-mainnet
  template:
    metadata:
      labels:
        app: parity-mainnet
    spec:
      containers:
      - name: parity-mainnet
        image: parity/parity:stable
        command: ["parity", "--tracing", "on", "--pruning", "archive","--jsonrpc-hosts", "all", "--jsonrpc-interface", "all"]
        ports:
        - containerPort: 8545
          name: port1
        - containerPort: 8546
          name: port2
        - containerPort: 30303
          name: port3
