apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: parity-mainnet
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parity-mainnet
  template:
    metadata:
      labels:
        app: parity-mainnet
    spec:
      volumes:
      - name: ethereum-parity-volume
        gcePersistentDisk:
          pdName: ethereum-parity-disk
          fsType: ext4
      securityContext:
        fsGroup: 1000
      containers:
      - name: parity-mainnet
        image: gcr.io/etheroscope/myparity:stable
        env:
        - name: PATH
          value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: TARGET
          value: "parity"
        - name: RUST_BACKTRACE
          value: "1"
        command: ["parity"]
        args: ["-d", "/ethereum-data", "--no-warp", "--tracing", "on", "--pruning", "archive","--jsonrpc-hosts", "all",
               "--jsonrpc-interface", "all", "--allow-ips=public", "--no-discovery"]
        ports:
        - containerPort: 8545
          name: port1mainnet
        - containerPort: 8546
          name: port2mainnet
        - containerPort: 30303
          name: port3mainnet
        volumeMounts:
        - name: ethereum-parity-volume
          mountPath: /ethereum-data/
