kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
  - protocol: TCP
    name: halo
    port: 5671
    targetPort: 5671
  - protocol: TCP
    name: halo2
    port: 5672
    targetPort: 5672
  - protocol: TCP
    name: halo3
    port: 4369
    targetPort: 4369
  - protocol: TCP
    name: halo4
    port: 25672
    targetPort: 25672
#  type: ClusterIP
  type: LoadBalancer
