kind: Service
apiVersion: v1
metadata:
  name: etheroscope-contract-info-service-load-balancer-8080
spec:
  selector:
    app: etheroscope-contract-info-service
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer