apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etheroscope-contract-info-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etheroscope-contract-info-service
  template:
    metadata:
      labels:
        app: etheroscope-contract-info-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: etheroscope-contract-info-service-container
        image: gcr.io/etheroscope/etheroscope-contract-info-service:latest
        env:
        - name: ETHEROSCOPEPARITYMAINNET
          value: "35.230.140.68:8545"
        - name: ETHEROSCOPEGETHHOST
          #          value: "10.3.255.188:8545" # rinkeby
          value: "10.3.240.197:8545"
        - name: ETHEROSCOPEMARIADB
          value: "10.3.240.97:8083"
        - name: ETHEROSCOPEDATAPOINTSSERVICE
          value: "35.246.65.214:80"
        - name: ETHEROSCOPESERVER
          value: "35.246.120.150:8080"
        - name: ETHEROSCOPEFRONTEND
          value: "35.242.161.116:80"
        imagePullPolicy: "Always"
